#!/bin/bash -ex

for target in {prereqs,base,server,asrclient}
do
    if [[ "${target}" == "base" ]]; then
        args="--no-cache"
    else
        args=""
    fi	
    docker build . ${args} -f Dockerfile.${target} -t skyman.azurecr.io/scratch/onprem/unimrcp:${target}
    if [[ "$1" == "push" ]]; then
        docker push skyman.azurecr.io/scratch/onprem/unimrcp:${target}
    fi
done

